feat: Выполнен дипломный проект согласно техническому заданию
ichDanch/java-explore-with-me-project pull request #1
Opened 2022-10-16 19:43 UTC by ichDanch

Постман тесты основного сервиса. По одному все тесты проходят. Если запустить коллекцию, то один тест валится (публичный просмотр всех евентов). Может быть это из-за обновления тестов.
![postman main passed](https://user-images.githubusercontent.com/94185700/196054355-879741cb-8663-4bd3-ac04-8fc94451feb6.JPG)
Тот самый тест, который при запуске коллекции не проходит. Возможно тест ожидает 2 евента, а приходят все создавшиеся из коллекции.
![postman main failed](https://user-images.githubusercontent.com/94185700/196054700-0aeaf054-2efa-4969-84f8-5cb2729dd03a.JPG)
Тесты постман сервиса статистики все проходят.
![postman stat passed](https://user-images.githubusercontent.com/94185700/196054800-a7c730ec-dfe3-449f-987f-7539a69ebc30.JPG)

2022-10-18 17:56 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/mainserver/compilation/model/Compilation.java
> +@Data
Не рекоммендуется использовать Data в JPA Entity

2022-10-18 17:59 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/mainserver/compilation/CompilationServiceImpl.java
> +    public CompilationDto pinCompilation(Long compId) {
unpinCompilation  и pinCompilation отличаются друг от друга только одним параметром. Убери дублирование, пожалуйста.

2022-10-18 18:00 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/mainserver/event/model/Event.java
> +@EqualsAndHashCode(onlyExplicitlyIncluded = true)
EqualsAndHashCode так же не рекоммендуется для JPA Entity

2022-10-18 18:01 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/mainserver/event/model/Event.java
> +@EqualsAndHashCode(onlyExplicitlyIncluded = true)
Поправь и в остальных Entity - не должно быть Data, EqualsAndhashCode

2022-10-18 18:02 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/mainserver/event/Repository/EventRepository.java
> +    Page<Event> findAllByAnnotationIgnoreCaseAndDescriptionIgnoreCaseAndCategoryIdInAndPaidAndEventDateBetween(
Этот метод никогда не используется

2022-10-18 18:04 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/mainserver/event/Repository/EventRepository.java
> +    findAllByAnnotationContainingIgnoreCaseOrDescriptionContainingIgnoreCaseAndCategoryIdInAndPaidAndEventDateBetween(
На мой взгляд гораздо нагляднее написать селект. Но тут на вкус и размер строки и время отладки так сказать товарищей нет ))
Комментарий из разряда "подискутировать" от какого размера лучше писать селект, а когда такую функцию

2022-10-18 18:06 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/mainserver/event/Service/EventServiceImpl.java
> +                        eventShortDtos.add(shortDto);
Попробуй эти if переписать. Во всех if сейчас выполняется одно и то же действие eventShortDtos.add(shortDto);
Может быть можно его вынести куда-то за if, или сделать один if

2022-10-18 18:07 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/mainserver/event/Service/EventServiceImpl.java
> +                            text, text, categories, paid, rangeStart, rangeEnd, pageWithElements)
Когда в функцию передают два одинаковых параметра это странно. Но может так нужно по бизнес логике

2022-10-18 18:11 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/mainserver/user/dto/UserDto.java
> +public class UserDto {
Класс не отличается вообще от UserShortDto. Предлагаю один из них удалить.

2022-10-18 18:15 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/mainserver/MainServerApplication.java
> +public class MainServerApplication {
Если приложение запустить, то оно падает
org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

2022-10-18 18:16 UTC, EvgenyKoptubenko commented on main-service/src/main/java/ru/practicum/mainserver/MainServerApplication.java
> +public class MainServerApplication {
mvn clean install тоже не работает
Caused by: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

2022-10-18 18:18 UTC, EvgenyKoptubenko commented
Проект гигантский, шо глаза разбегаются как это ревьюить.
Когда проект такой огромный нужно добавить readme.md,  в котором написано как этот проект запускать. 
Еще было бы здорово иметь какой-то док в проекте, который рассказывает о чем этот проект и что должен делать.

2022-10-18 18:19 UTC, EvgenyKoptubenko requested changes
Проект гигантский. Работа сделана колоссальная.
Замечаний совсем немного. Поправь, пожалуйста.

2022-10-19 16:53 UTC, ichDanch commented on main-service/src/main/java/ru/practicum/mainserver/compilation/CompilationServiceImpl.java
> +    public CompilationDto pinCompilation(Long compId) {
Сделал одним методом.

2022-10-19 17:02 UTC, ichDanch commented on main-service/src/main/java/ru/practicum/mainserver/event/Service/EventServiceImpl.java
> +                            text, text, categories, paid, rangeStart, rangeEnd, pageWithElements)
По заданию текст надо найти в аннотациях или в описании. Не нашел способа как написать через JPA метод, чтобы передать один параметр и искать в двух столбцах. Переписал метод через JPQL.

2022-10-19 17:03 UTC, ichDanch commented on main-service/src/main/java/ru/practicum/mainserver/event/Service/EventServiceImpl.java
> +                        eventShortDtos.add(shortDto);
От if уйти не удалось, но считаю упростил конструкцию и переписал метод целиком.

2022-10-19 17:27 UTC, ichDanch commented on main-service/src/main/java/ru/practicum/mainserver/event/model/Event.java
> +@EqualsAndHashCode(onlyExplicitlyIncluded = true)
Можно поинтересоваться почему? А если нужно переопределить Equals и HashCode, вручную писать, без аннотаций? Буду благодарен за ссылку на какую-нибудь статью/документацию на эту тему.
Во всех entity убрал Data и EqualsAndhashCode, добавил Getter и Setter.

2022-10-20 17:39 UTC, ichDanch commented on main-service/src/main/java/ru/practicum/mainserver/user/dto/UserDto.java
> +public class UserDto {
Поправил. Теперь UserShortDto отличается от UserDto одним полем.

2022-10-20 20:00 UTC, ichDanch commented on main-service/src/main/java/ru/practicum/mainserver/MainServerApplication.java
> +public class MainServerApplication {
Не пойму с чем связана эта ошибка. У меня проект собирается и запускается корректно.
Тест на checkstyle прошел успешно.
![checkstyle success](https://user-images.githubusercontent.com/94185700/197043857-4015727e-49ef-4aa7-91ac-c710fc558b6e.JPG)
mvn clean install успешно.
![MvnCleanInstall success](https://user-images.githubusercontent.com/94185700/197043991-7299d777-468b-4b4b-9390-47baa48672d5.JPG)
mvn clean package успешно.
![MvnCleanPackage success](https://user-images.githubusercontent.com/94185700/197044052-ca8f94f1-5cc8-4506-91cc-7146b0a95ec4.JPG)
Лог запуска docker-compose up успешно. Все постман тесты тоже проходят, так же как и локально.
https://pastebin.com/sqfBJ9Dd

2022-10-21 19:10 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо. На будущее, например, когда будут спрашивать на собеседовании, то в проекте еще должно быть:
* 		Healthcheck (отдельный эндпоинт, который возвращает данные о том как себя чувствует приложение) - например описать как работает Spring Actuator
* 		На основе Healthcheck можно делать мониторинг, который будет периодически дергать этот эндпоинт и если что-то в healthcheck сломалось, то присылает алерты
* 		Так же в проекте должна быть документация, которая автоматически собирается - Docsify, например
* 		Так что должно быть отдельное приложение, которое собирает проект, создает артифакт и складывает его в хранилище. В Github тоже можно такое сделать.
* 		Во время код ревью должен подключаться Sonar для проверок.
* 		Во время пул реквеста так же должно подсчитываться покрытие кода тестами
* 		Приложение должно быть защищено, т.е. неавторизованные пользователи не должны иметь доступ к эндпоинтам. Почитай про OAUTH2
* 		В пул реквестах должно быть настроено минимальное количество апруверов, которые должны проверить и заапрувить пул реквест перед тем как его можно мерджить
* 		Все должно быть покрыто юнит тестами, так же должны быть написаны BDD тесты.
* 		Все, что не дает коду пройти в прод называется Quality Gates. К таким quality gates можно причислить: jUnit tests, BDD tests, Sonar, Pull Requests checks, code coverage, Catchpoint tests, Performance tests, Browserstack tests.
* 		Так же в приложении должен быть код, который создает инфраструктуру. Например, если ты хостишься в Amazon, то через Terraform нужно создать инфру.
* 		Дополнительный мониториг бизнес фич. У тебя должны быть графики о том как дела у приложения и у клиентов. И так же настроены алерты, если что-то пошло не так.

2022-10-22 11:07 UTC, merged